// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResidentialPortalCLI.OData.ODataProxy.Generators.Dto
{
    using Microsoft.Data.Edm;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class DtoTemplate : DtoTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing EI.RP.CoreServices.Ports." +
                    "OData;\r\nusing System.ComponentModel.DataAnnotations;\r\nnamespace EI.RP.DataModels" +
                    ".Sap.");
            
            #line 8 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RepositoryName));
            
            #line default
            #line hidden
            this.Write(".Dtos\r\n{\r\n/******************************\r\nTHIS CLASS WAS GENERATED, DO NOT EDIT " +
                    "MANUALLY. \r\n\r\nFor customizations, create and edit a partial file instead\r\n******" +
                    "************************/\r\n    [CrudOperations(CanAdd=");
            
            #line 15 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operations.CanAdd.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(", CanUpdate=");
            
            #line 15 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operations.CanUpdate.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(", CanDelete=");
            
            #line 15 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operations.CanDelete.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(", CanQuery=");
            
            #line 15 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operations.CanQuery.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(")]\r\n\tpublic partial class ");
            
            #line 16 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(" : ODataDtoModel\r\n\t{\r\n");
            
            #line 18 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if (CollectionName!=null){
            
            #line default
            #line hidden
            this.Write("public override string CollectionName()=>\"");
            
            #line 18 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CollectionName));
            
            #line default
            #line hidden
            this.Write("\";");
            
            #line 18 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" public override object[] UniqueId()\r\n\t\t{\r\n\r\n\t\t\treturn new object []\r\n\t\t\t{\r\n");
            
            #line 24 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
foreach (var key in this.PrimaryKeys){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 25 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key));
            
            #line default
            #line hidden
            this.Write(",\r\n\r\n");
            
            #line 27 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t};\r\n\t\t}\r\n        public  override string  GetEntityContainerName()\r\n        {\r" +
                    "\n            return \"");
            
            #line 32 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContainerName));
            
            #line default
            #line hidden
            this.Write("\";\r\n        }\r\n\r\n");
            
            #line 35 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
foreach (var property in this.Properties){
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 36 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if(!property.IsNullable){
            
            #line default
            #line hidden
            this.Write("        [Required(AllowEmptyStrings = true)]\r\n\r\n");
            
            #line 39 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 40 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if(property.MaxLength!=null){
            
            #line default
            #line hidden
            this.Write("        [StringLength(");
            
            #line 41 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.MaxLength));
            
            #line default
            #line hidden
            this.Write(")]\r\n\r\n");
            
            #line 43 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 44 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if(property.CanSort){
            
            #line default
            #line hidden
            this.Write("        [Sortable]\r\n\r\n");
            
            #line 47 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 48 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if(property.CanFilter){
            
            #line default
            #line hidden
            this.Write("        [Filterable]\r\n\r\n");
            
            #line 51 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 52 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if(!property.ReturnType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual ");
            
            #line 53 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 53 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; } ");
            
            #line 53 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DefaultValue));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 55 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
if(property.ReturnType.StartsWith("DateTime")){
            
            #line default
            #line hidden
            this.Write("        public virtual ");
            
            #line 56 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 56 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n        {\r\n            get => _");
            
            #line 58 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tset => _");
            
            #line 59 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = CompensateSapDateTimeBug(value);\r\n        } \r\n        private ");
            
            #line 61 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ReturnType));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 61 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            
            #line 61 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DefaultValue));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 62 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 63 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\ResidentialPortalCLI\OData\ODataProxy\Generators\Dto\DtoTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class DtoTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
