// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResidentialPortalCLI.Flows.CreateNewFlow.Builders.FlowInitializer
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class FlowInitializerTemplate  : FlowInitializerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Threading.Tasks;
using EI.RP.CoreServices.Cqrs.Commands;
using EI.RP.CoreServices.Cqrs.Queries;
using EI.RP.CoreServices.Http.Session;
using EI.RP.UiFlows.Core.Configuration;
using EI.RP.UiFlows.Core.DataSources;
using EI.RP.UiFlows.Core.Flows.Initialization;
using EI.RP.UiFlows.Core.Flows.Initialization.Models;
using EI.RP.UiFlows.Core.Flows.Screens;
using EI.RP.UiFlows.Core.Flows.Screens.Models;
using EI.RP.WebApp.Flows.AppFlows.");
            
            #line 13 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write(".FlowDefinitions;\r\n\r\nnamespace EI.RP.WebApp.Flows.AppFlows.");
            
            #line 15 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write(".Steps\r\n{\r\n    /// <summary>\r\n\t///this is the entry point of the flow (");
            
            #line 18 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write(") the initial screen is resolved here and as you have the option of holding all t" +
                    "he flow context here or in the steps\r\n\t/// </summary>\r\n\tpublic class ");
            
            #line 20 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write("FlowInitializer : UiFlowInitializationStep<ResidentialPortalFlowType,\r\n\t\t");
            
            #line 21 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write("FlowInitializer.RootScreenModel>\r\n\t{\r\n\t\tprivate readonly IUserSessionProvider _us" +
                    "erSessionProvider;\r\n\t\tprivate readonly IDomainQueryResolver _domainQueryResolver" +
                    ";\r\n\t\tprivate readonly IDomainCommandDispatcher _domainCommandDispatcher;\r\n\r\n\t\tpu" +
                    "blic ");
            
            #line 27 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write(@"FlowInitializer(IUserSessionProvider userSessionProvider,
			IDomainQueryResolver domainQueryResolver,
			IDomainCommandDispatcher domainCommandDispatcher)
		{
			_userSessionProvider = userSessionProvider;
			_domainQueryResolver = domainQueryResolver;
			_domainCommandDispatcher = domainCommandDispatcher;
		}

		public override ResidentialPortalFlowType InitializerOfFlowType => ResidentialPortalFlowType.");
            
            #line 36 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write(@";

		public override bool Authorize()
		{
            throw new NotImplementedException(""//TODO: samplereturn !_userSessionProvider.IsAnonymous()"")			;
		}

		public override IScreenFlowConfigurator OnDefiningAdditionalInitialStateTransitions(
			IScreenFlowConfigurator preStartCfg, UiFlowContextData contextData)
		{
			return preStartCfg
				.OnEventNavigatesTo(ScreenEvent.ErrorOccurred, ");
            
            #line 47 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write("Step.ShowFlowGenericError)\r\n\t\t\t\t.OnEventNavigatesTo(ScreenEvent.Start, ");
            
            #line 48 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write(@"Step.InitialScreen);

		}

		protected override async Task<RootScreenModel> OnBuildStartData(UiFlowContextData contextData,
			RootScreenModel data)
		{
			//TODO: POPULATE THE START DATA

			return data;
		}

		protected override ScreenEvent ResolveInitializationEventToTrigger(
			ScreenEvent defaultEventToTriggerAfter,
			UiFlowScreenModel screenModel)
		{
			//TODO: implement here the logic resolve the initial event that navigates to the initial screen to show
			return base.ResolveInitializationEventToTrigger(defaultEventToTriggerAfter, screenModel);
		}


		public class RootScreenModel : InitialFlowScreenModel, I");
            
            #line 69 "C:\DEVELOPMENT\CODE\newResidentialPortal1\src\Ei.Rp.CodeGen\Flows\CreateNewFlow\Builders\FlowInitializer\FlowInitializerTemplate .tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.FlowName));
            
            #line default
            #line hidden
            this.Write("Input\r\n\t\t{\r\n\t\t\t\r\n\t\t}\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class FlowInitializerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
